services:
  website:
    build:
      context: .
      target: runtime
    ports:
      - "8383:80"
    restart: unless-stopped
  exporter:
    build:
      context: .
      target: exporter
    env_file:
      - packages/exporter/.env
    volumes:
      - exporter-data:/app/data/output
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  exporter-data:
